[package]
edition.workspace    = true
name                 = "moltis-web"
repository.workspace = true
version.workspace    = true

[dependencies]
anyhow          = { workspace = true }
askama          = { workspace = true }
axum            = { workspace = true }
axum-extra      = { features = ["cookie"], workspace = true }
base64          = { workspace = true }
futures         = { workspace = true }
gix             = { workspace = true }
include_dir     = { workspace = true }
moltis-config   = { workspace = true }
moltis-cron     = { workspace = true }
moltis-gateway  = { workspace = true }
moltis-skills   = { workspace = true }
moltis-tools    = { workspace = true }
portable-pty    = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
sysinfo         = { workspace = true }
tokio           = { workspace = true }
tokio-util      = { workspace = true }
tracing         = { workspace = true }
uuid            = { workspace = true }
which           = { workspace = true }

[features]
default            = []
metrics            = ["moltis-gateway/metrics"]
push-notifications = ["moltis-gateway/push-notifications"]
tailscale          = ["moltis-gateway/tailscale"]
voice              = []
graphql            = []

[lints]
workspace = true
